version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    groups:
      actions-org:
        patterns:
          - "actions/*"
          - "github/*"
        update-types:
          - "minor"
          - "patch"
      azure-org:
        patterns:
          - "azure/*"
        update-types:
          - "minor"
          - "patch"
